apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
  selector:
    app: kafka_app
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka_app
  template:
    metadata:
      labels:
        app: kafka_app
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:2.11-2.0.0
        ports:
        - containerPort: 9092
        env:
          - name : BROKER_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name : KAFKA_ADVERTISED_LISTENERS
            value : "PLAINTEXT://$(BROKER_IP):9092"
          - name : KAFKA_LISTENERS
            value : "PLAINTEXT://0.0.0.0:9092"
          - name : KAFKA_ZOOKEEPER_CONNECT
            value : zookeeper:2181
          - name : KAFKA_CREATE_TOPICS
            value : "data-retrieval:1:1,model-execution:1:1,postprocessing-analysis:1:1,usermanagement:1:1,sessionmanagement:1:1,session-update:1:1"

