apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-execution-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-execution
  template:
    metadata:
      labels:
        app: model-execution
    spec:
      containers:
      - name: model-execution
        image: adiselv/captivate.model-execution:latest
        imagePullPolicy: Always
        env:
          - name : KAFKA_SERVER
            value : kafka-service:9092
          - name : MODEL_EXECUTION_DB
            value : mongodb://model-execution-db:27017

