apiVersion: v1
kind: Service
metadata:
  name: post-process-db
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app: post-process-db

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-process-db-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-process-db
  template:
    metadata:
      labels:
        app: post-process-db
    spec:
      containers:
      - name: post-process-db
        image: mongo:4.0.4
        ports:
        - containerPort: 27017

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-process-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-process
  template:
    metadata:
      labels:
        app: post-process
    spec:
      containers:
      - name: post-process
        image: adiselv/captivate.post-process:latest
        imagePullPolicy: Always
        env:
          - name : KAFKA_SERVER
            value : kafka-service:9092
          - name : POST_PROCESSING_DB
            value : mongodb://post-process-db:27017

