apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-process-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-process
  template:
    metadata:
      labels:
        app: post-process
    spec:
      containers:
      - name: post-process
        image: adiselv/captivate.post-process:latest
        imagePullPolicy: Always
        env:
          - name : KAFKA_SERVER
            value : kafka-service:9092
          - name : POST_PROCESSING_DB
            value : mongodb://post-process-db:27017

