apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-management-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-management
  template:
    metadata:
      labels:
        app: session-management
    spec:
      containers:
      - name: session-management
        image: adiselv/captivate.session-management:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3005
        env:
          - name : KAFKA_SERVER
            value : kafka-service:9092
          - name : SESSION_MANAGEMENT_DB
            value : mongodb://session-management-db:27017

