apiVersion: v1
kind: Service
metadata:
  name: user-management
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8181
    targetPort: 8181
  selector:
    app: user-management
---
apiVersion: v1
kind: Service
metadata:
  name: user-management-db
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: user-management-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-db-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management-db
  template:
    metadata:
      labels:
        app: user-management-db
    spec:
      containers:
      - name: user-management-db
        image: mysql:8.0.19
        ports:
        - containerPort: 3306
        env:
          - name : MYSQL_ROOT_PASSWORD
            value : root.CAP2020
          - name : MYSQL_DATABASE
            value : ads_docker

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
      - name: user-management
        image: adiselv/captivate.user-management:0.0.1
        ports:
        - containerPort: 8181
        env:
          - name : MYSQL_URL
            value : user-management-db:3306
          - name : MYSQL_USERNAME
            value : root
          - name : MYSQL_ROOT_PASSWORD
            value : root.CAP2020
          - name : USER_MANAGEMENT_DB
            value : ads_docker

