language: python
services:
  - docker

before_install: cd model-execution
script:
  - echo "TODO - add unit test and integration tests"
after-success:
  - docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD
  - docker build -t $DOCKER_USER_NAME/captivate.model-execution:$TRAVIS_COMMIT .
  - docker tag $DOCKER_USER_NAME/captivate.model-execution:$TRAVIS_COMMIT $DOCKER_USER_NAME/captivate.model-execution:latest
  - docker push $DOCKER_USER_NAME/captivate.model-execution:$TRAVIS_COMMIT
  - docker push $DOCKER_USER_NAME/captivate.model-execution:latest
  - curl -X POST http://captivate:$JENKINS_USER_TOKEN@$JENKINS_URL/job/deploy_model_execution/build?token=$JENKINS_JOB_TOKEN

branches:
  only:
    - deploy/model-execution