language: node_js
node_js:
  - 7
  
services:
  - docker

before_install: cd WeatherApp
script:
  - echo "TODO - add unit test and integration tests"
after-success:
  - docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD
  - docker build -t $DOCKER_USER_NAME/captivate.ui:$TRAVIS_COMMIT .
  - docker tag $DOCKER_USER_NAME/captivate.ui:$TRAVIS_COMMIT $DOCKER_USER_NAME/captivate.ui:latest
  - docker push $DOCKER_USER_NAME/captivate.ui:latest
  - docker push $DOCKER_USER_NAME/captivate.ui:$TRAVIS_COMMIT
  - curl -X POST http://captivate:$JENKINS_USER_TOKEN@$JENKINS_URL/job/deploy_ui/build?token=$JENKINS_JOB_TOKEN

branches:
  only:
    - deploy/user-interface