language: python
services:
  - docker

before_install: cd postprocessing-analysis
script:
  - echo "TODO - add unit test and integration tests"
after-success:
  - docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD
  - docker build -t $DOCKER_USER_NAME/captivate.post-process:$TRAVIS_COMMIT .
  - docker tag $DOCKER_USER_NAME/captivate.post-process:$TRAVIS_COMMIT $DOCKER_USER_NAME/captivate.post-process:latest
  - docker push $DOCKER_USER_NAME/captivate.post-process:latest
  - docker push $DOCKER_USER_NAME/captivate.post-process:$TRAVIS_COMMIT
  - curl -X POST http://captivate:$JENKINS_USER_TOKEN@$JENKINS_URL/job/deploy_post_process/build?token=$JENKINS_JOB_TOKEN

branches:
  only:
    - deploy/post-process