version: '3'

services:

  mysql-container:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: root.CAP2020
      MYSQL_DATABASE: ads_docker
    ports:
      - "3308:3306"
 
  admin:    
    image: adminer    
    ports:      
      - "8081:8080"