version: '3'

services:

  mysql-container:
    container_name: mysql-container
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: root.CAP2020
      MYSQL_DATABASE: ads_docker
    ports:
      - 3308:3306
    networks:
      - user-mgmt-network

  user-mgmt:
    image: user-mgmt-image
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8181:8181
    environment:
      WAIT_HOSTS: mysql-container:3306
    networks:
      - user-mgmt-network
    depends_on:
      - mysql-container
    links:
      - mysql-container

networks:
  user-mgmt-network:
    driver: bridge